apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox-echo
  name: busybox-echo
spec:
  containers:
  - command:
    - echo
    - Hello world
    image: busybox
    name: busybox-echo
  dnsPolicy: ClusterFirst
  restartPolicy: Always