apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hr-app
  name: hr-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hr-app
  template:
    metadata:
      labels:
        app: hr-app
    spec:
      containers:
      - image: nginx:1.18
        name: nginx
