kind: PersistentVolume
apiVersion: v1
metadata:
  name: myvolume-practice
spec:
  storageClassName: normal
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  hostPath:
    path: /etc/foo