apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-test
  name: nginx-test
spec:
  nodeName: kind-worker2
  containers:
  - image: nginx
    name: nginx-test
    env:
    - name: var1
      value: "val1"
  dnsPolicy: ClusterFirst
  restartPolicy: Always