apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc-practice
  labels:
    type: local
spec:
  storageClassName: normal
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi