apiVersion: v1
kind: Pod
metadata:
  name: nginx-cm
spec:
  containers:
    - name: nginx-container
      image: nginx
      envFrom:
      - configMapRef:
          name: anotherone
  restartPolicy: Never