apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret
spec:
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
      - name: mysecret
        mountPath: /etc/foo
  volumes:
    - name: mysecret
      secret:
        secretName: mysecret
  restartPolicy: Never