apiVersion: v1
kind: Pod
metadata:
  name: redis-storage
spec:
  volumes:
    - name: myvolume
      emptyDir: {}
      persistentVolumeClaim:
        claimName: mypvc
  containers:    
    - name: redis-storage
      image: redis:alpine
      volumeMounts:
        - mountPath: "/data/redis"
          name: myvolume